version: '3.8'

services:
  # MongoDB (giữ lại cho trường hợp cần dùng local)
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  # API Gateway
  api-gateway:
    build: ./gateway/api-gateway
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb+srv://admin:admin@datvephim.pmydnk2.mongodb.net/?retryWrites=true&w=majority&appName=DatVePhim
      - AWS_ACCESS_KEY_ID=AKIA6DHGUQZQGQMCRAHX
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_REGION=ap-southeast-2
      - SQS_BOOKING_CREATED_URL=https://sqs.ap-southeast-2.amazonaws.com/968998815328/booking-created
      - SQS_PAYMENT_PROCESSED_URL=https://sqs.ap-southeast-2.amazonaws.com/968998815328/payment-processed
      - SQS_SEATS_BOOKED_URL=https://sqs.ap-southeast-2.amazonaws.com/968998815328/seats-booked
    networks:
      - app-network

  # Movie Service
  movie-service:
    build: ./services/movie-service
    ports:
      - "8001:8000"
    environment:
      - MONGODB_URI=mongodb+srv://admin:admin@datvephim.pmydnk2.mongodb.net/?retryWrites=true&w=majority&appName=DatVePhim
      - AWS_ACCESS_KEY_ID=AKIA6DHGUQZQGQMCRAHX
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_REGION=ap-southeast-2
    networks:
      - app-network

  # Booking Service
  booking-service:
    build: ./services/booking-service
    ports:
      - "8002:8000"
    environment:
      - MONGODB_URI=mongodb+srv://admin:admin@datvephim.pmydnk2.mongodb.net/?retryWrites=true&w=majority&appName=DatVePhim
      - AWS_ACCESS_KEY_ID=AKIA6DHGUQZQGQMCRAHX
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_REGION=ap-southeast-2
      - SQS_BOOKING_CREATED_URL=https://sqs.ap-southeast-2.amazonaws.com/968998815328/booking-created
      - SQS_PAYMENT_PROCESSED_URL=https://sqs.ap-southeast-2.amazonaws.com/968998815328/payment-processed
      - SQS_SEATS_BOOKED_URL=https://sqs.ap-southeast-2.amazonaws.com/968998815328/seats-booked
    networks:
      - app-network

  # Customer Service
  customer-service:
    build: ./services/customer-service
    ports:
      - "8003:8000"
    environment:
      - MONGODB_URI=mongodb+srv://admin:admin@datvephim.pmydnk2.mongodb.net/?retryWrites=true&w=majority&appName=DatVePhim
      - AWS_ACCESS_KEY_ID=AKIA6DHGUQZQGQMCRAHX
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_REGION=ap-southeast-2
    networks:
      - app-network

  # Payment Service
  payment-service:
    build: ./services/payment-service
    ports:
      - "8004:8000"
    environment:
      - MONGODB_URI=mongodb+srv://admin:admin@datvephim.pmydnk2.mongodb.net/?retryWrites=true&w=majority&appName=DatVePhim
      - AWS_ACCESS_KEY_ID=AKIA6DHGUQZQGQMCRAHX
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_REGION=ap-southeast-2
      - SQS_PAYMENT_PROCESSED_URL=https://sqs.ap-southeast-2.amazonaws.com/968998815328/payment-processed
    networks:
      - app-network

  # Seat Service
  seat-service:
    build: ./services/seat-service
    ports:
      - "8005:8000"
    environment:
      - MONGODB_URI=mongodb+srv://admin:admin@datvephim.pmydnk2.mongodb.net/?retryWrites=true&w=majority&appName=DatVePhim
      - AWS_ACCESS_KEY_ID=AKIA6DHGUQZQGQMCRAHX
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_REGION=ap-southeast-2
      - SQS_SEATS_BOOKED_URL=https://sqs.ap-southeast-2.amazonaws.com/968998815328/seats-booked
    networks:
      - app-network

  # Notification Service
  notification-service:
    build: ./services/notification-service
    ports:
      - "8006:8000"
    environment:
      - MONGODB_URI=mongodb+srv://admin:admin@datvephim.pmydnk2.mongodb.net/?retryWrites=true&w=majority&appName=DatVePhim
      - AWS_ACCESS_KEY_ID=AKIA6DHGUQZQGQMCRAHX
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_REGION=ap-southeast-2
      - SQS_BOOKING_CREATED_URL=https://sqs.ap-southeast-2.amazonaws.com/968998815328/booking-created
      - SQS_PAYMENT_PROCESSED_URL=https://sqs.ap-southeast-2.amazonaws.com/968998815328/payment-processed
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
