version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  # Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - app-network

  # API Gateway
  api-gateway:
    build: ./backend/api-gateway
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    depends_on:
      - mongodb
      - kafka
    networks:
      - app-network

  # Movie Service
  movie-service:
    build: ./backend/movie-service
    ports:
      - "8001:8000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    depends_on:
      - mongodb
      - kafka
    networks:
      - app-network

  # Booking Service
  booking-service:
    build: ./backend/booking-service
    ports:
      - "8002:8000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    depends_on:
      - mongodb
      - kafka
    networks:
      - app-network

  # Customer Service
  customer-service:
    build: ./backend/customer-service
    ports:
      - "8003:8000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    depends_on:
      - mongodb
      - kafka
    networks:
      - app-network

  # Payment Service
  payment-service:
    build: ./backend/payment-service
    ports:
      - "8004:8000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    depends_on:
      - mongodb
      - kafka
    networks:
      - app-network

  # Seat Service
  seat-service:
    build: ./backend/seat-service
    ports:
      - "8005:8000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    depends_on:
      - mongodb
      - kafka
    networks:
      - app-network

  # Notification Service
  notification-service:
    build: ./backend/notification-service
    ports:
      - "8006:8000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    depends_on:
      - mongodb
      - kafka
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
