version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  # API Gateway
  api-gateway:
    build: ./backend/api-gateway
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - AWS_ACCESS_KEY_ID=AKIAVXZ2UJQZQZQZQZQZ
      - AWS_SECRET_ACCESS_KEY=your_secret_key
      - AWS_REGION=ap-southeast-2
      - SQS_BOOKING_CREATED_URL=https://sqs.ap-southeast-2.amazonaws.com/968998815328/booking-created
      - SQS_PAYMENT_PROCESSED_URL=https://sqs.ap-southeast-2.amazonaws.com/968998815328/payment-processed
      - SQS_SEATS_BOOKED_URL=https://sqs.ap-southeast-2.amazonaws.com/968998815328/seats-booked
    depends_on:
      - mongodb
    networks:
      - app-network

  # Movie Service
  movie-service:
    build: ./backend/movie-service
    ports:
      - "8001:8000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - AWS_ACCESS_KEY_ID=AKIAVXZ2UJQZQZQZQZQZ
      - AWS_SECRET_ACCESS_KEY=your_secret_key
      - AWS_REGION=ap-southeast-2
    depends_on:
      - mongodb
    networks:
      - app-network

  # Booking Service
  booking-service:
    build: ./backend/booking-service
    ports:
      - "8002:8000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - AWS_ACCESS_KEY_ID=AKIAVXZ2UJQZQZQZQZQZ
      - AWS_SECRET_ACCESS_KEY=your_secret_key
      - AWS_REGION=ap-southeast-2
      - SQS_BOOKING_CREATED_URL=https://sqs.ap-southeast-2.amazonaws.com/968998815328/booking-created
      - SQS_PAYMENT_PROCESSED_URL=https://sqs.ap-southeast-2.amazonaws.com/968998815328/payment-processed
      - SQS_SEATS_BOOKED_URL=https://sqs.ap-southeast-2.amazonaws.com/968998815328/seats-booked
    depends_on:
      - mongodb
    networks:
      - app-network

  # Customer Service
  customer-service:
    build: ./backend/customer-service
    ports:
      - "8003:8000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - AWS_ACCESS_KEY_ID=AKIAVXZ2UJQZQZQZQZQZ
      - AWS_SECRET_ACCESS_KEY=your_secret_key
      - AWS_REGION=ap-southeast-2
    depends_on:
      - mongodb
    networks:
      - app-network

  # Payment Service
  payment-service:
    build: ./backend/payment-service
    ports:
      - "8004:8000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - AWS_ACCESS_KEY_ID=AKIAVXZ2UJQZQZQZQZQZ
      - AWS_SECRET_ACCESS_KEY=your_secret_key
      - AWS_REGION=ap-southeast-2
      - SQS_PAYMENT_PROCESSED_URL=https://sqs.ap-southeast-2.amazonaws.com/968998815328/payment-processed
    depends_on:
      - mongodb
    networks:
      - app-network

  # Seat Service
  seat-service:
    build: ./backend/seat-service
    ports:
      - "8005:8000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - AWS_ACCESS_KEY_ID=AKIAVXZ2UJQZQZQZQZQZ
      - AWS_SECRET_ACCESS_KEY=your_secret_key
      - AWS_REGION=ap-southeast-2
      - SQS_SEATS_BOOKED_URL=https://sqs.ap-southeast-2.amazonaws.com/968998815328/seats-booked
    depends_on:
      - mongodb
    networks:
      - app-network

  # Notification Service
  notification-service:
    build: ./backend/notification-service
    ports:
      - "8006:8000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - AWS_ACCESS_KEY_ID=AKIA6DHGUQZQGQMCRAHX
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_REGION=ap-southeast-2
      - SQS_BOOKING_CREATED_URL=https://sqs.ap-southeast-2.amazonaws.com/968998815328/booking-created
      - SQS_PAYMENT_PROCESSED_URL=https://sqs.ap-southeast-2.amazonaws.com/968998815328/payment-processed
    depends_on:
      - mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
